menuItems=[
        "coffee",
        "olives",
        "celery",
        "tea",
        "radishes",
        "mashed potatoes",
        "boiled potatoes",
        "fruit",
        "milk",
        "chicken salad",
        "vanilla ice cream",
        "cocoa",
        "cheese",
        "lettuce salad",
        "lobster salad",
        "chocolate",
        "string beans",
        "apple pie",
        "sardines",
        "oranges",
        "american cheese",
        "green peas",
        "assorted cakes",
        "apollinaris",
        "french fried potatoes",
        "potato salad",
        "baked potatoes",
        "stewed prunes",
        "roquefort",
        "ham",
        "roast beef",
        "apples",
        "chocolate ice cream",
        "stewed tomatoes",
        "bananas",
        "sliced tomatoes",
        "lima beans",
        "camembert",
        "roquefort cheese",
        "cigars",
        "cucumbers",
        "ice cream",
        "edam cheese",
        "little neck clams",
        "swiss cheese",
        "demi tasse",
        "tomato juice",
        "crackers",
        "spinach",
        "cream cheese",
        "assorted cake",
        "cafe",
        "lettuce",
        "raisins",
        "sirloin steak",
        "cauliflower",
        "grapes",
        "blue points",
        "cup custard",
        "petits fours",
        "ripe olives",
        "demi-tasse",
        "orange",
        "french peas",
        "consomme",
        "fruits",
        "buttermilk",
        "tomato salad",
        "biscuit tortoni",
        "boiled rice",
        "kaffee",
        "iced tea",
        "corned beef",
        "succotash",
        "charlotte russe",
        "lobster cocktail",
        "cucumber salad",
        "salted almonds",
        "dessert",
        "benedictine",
        "cigarettes",
        "brussels sprouts",
        "romaine salad",
        "lyonnaise potatoes",
        "marmalade",
        "dry toast",
        "grape fruit",
        "apple sauce",
        "tongue",
        "camembert cheese",
        "bread and butter",
        "queen olives",
        "little necks",
        "chow chow",
        "chicken",
        "cold roast beef",
        "milk toast",
        "watermelon",
        "macaroons",
        "lettuce and tomato salad",
        "fried egg plant",
        "shrimp cocktail",
        "club sandwich",
        "pears",
        "chicken sandwich",
        "broiled ham",
        "baked apple",
        "ham sandwich",
        "strawberry ice cream",
        "mutton chops",
        "lamb chops",
        "corned beef hash",
        "brie",
        "creme de menthe",
        "cafe noir",
        "french pastry",
        "sweet pickles",
        "cold ham",
        "mince pie",
        "coffee ice cream",
        "roman punch",
        "smoked salmon",
        "peach melba",
        "welsh rarebit",
        "fruit salad",
        "shrimp salad",
        "assorted cakes",
        "stewed corn",
        "asparagus",
        "tenderloin steak",
        "ham and eggs",
        "scrambled eggs",
        "fried potatoes",
        "sauterne",
        "pumpkin pie",
        "orange juice",
        "fried eggs",
        "iced coffee",
        "white rock",
        "rice pudding",
        "pear",
        "boiled eggs",
        "escarole salad",
        "baked apple with cream",
        "oatmeal",
        "cherrystones",
        "nuts",
        "chicory salad",
        "salad",
        "peach pie",
        "maraschino",
        "cafe parfait",
        "half grapefruit",
        "buttered toast",
        "green olives",
        "caviar",
        "sanka",
        "neapolitan ice cream",
        "edam",
        "squab",
        "figs",
        "turkish coffee",
        "cream toast",
        "clam chowder",
        "beets",
        "cantaloupe",
        "nesselrode pudding",
        "blue point oysters",
        "gorgonzola",
        "new string beans",
        "bacon and eggs",
        "stuffed olives",
        "artichoke",
        "combination salad",
        "tongue sandwich",
        "oyster cocktail",
        "ginger ale",
        "orange marmalade",
        "sliced cucumbers",
        "tomatoes",
        "grapefruit",
        "cape cods",
        "anchovies",
        "pickles",
        "lemonade",
        "turkey",
        "gherkins",
        "cold slaw",
        "lamb",
        "gruyere",
        "neufchatel",
        "orange water ice",
        "cocktail sauce",
        "toast",
        "rolls",
        "oyster stew",
        "liqueurs",
        "postum",
        "lemon water ice",
        "hominy",
        "almonds",
        "pound cake",
        "fried sweet potatoes",
        "vanilla ice cream",
        "saratoga chips",
        "celery salad",
        "cherrystone clams",
        "new peas",
        "golden buck",
        "grapefruit juice",
        "chicken broth",
        "gorgonzola cheese",
        "waldorf salad",
        "sherry",
        "plums",
        "pork chops",
        "stewed tomatoes",
        "fruit cocktail",
        "sweet potatoes",
        "french coffee",
        "salted nuts",
        "pickled beets",
        "stewed prunes",
        "thee",
        "creamed spinach",
        "saute potatoes",
        "green peas",
        "radis",
        "small steak",
        "hot rolls",
        "cakes",
        "meringue glacee",
        "chicken salad",
        "johannis",
        "cold corned beef",
        "russian dressing",
        "port",
        "tomato",
        "chiffonade salad",
        "anisette",
        "mashed turnips",
        "pontet canet",
        "french peas",
        "clam broth",
        "liederkranz cheese",
        "green apple pie",
        "cake",
        "french dressing",
        "calf's liver and bacon",
        "cream",
        "virginia ham",
        "new lima beans",
        "watercress",
        "brie cheese",
        "candied sweet potatoes",
        "little neck clams",
        "sardine sandwich",
        "neufchatel cheese",
        "lynnhavens",
        "green corn",
        "amontillado",
        "watercress salad",
        "crab flake cocktail",
        "malaga grapes",
        "poached eggs on toast",
        "buckwheat cakes",
        "roquefort cheese",
        "roquefort cheese",
        "shirred eggs",
        "raspberry water ice",
        "roast chicken",
        "lady fingers",
        "squab chicken",
        "plover",
        "macaroni au gratin",
        "strawberries and cream",
        "st. julien",
        "niersteiner",
        "manhattan",
        "pineapple juice",
        "tomato juice cocktail",
        "potatoes au gratin",
        "congress water",
        "currant jelly",
        "graham bread",
        "fresh fruit",
        "apple",
        "green turtle soup",
        "lettuce salad",
        "salt mackerel",
        "cucumber",
        "chartreuse",
        "absinthe",
        "chow-chow",
        "beluga caviar",
        "stuffed celery",
        "curacao",
        "dill pickles",
        "pineapple",
        "pickled walnuts",
        "mixed grill",
        "preserves",
        "lobster salad",
        "martini",
        "plain omelette",
        "tomato soup",
        "mallard duck",
        "roast mutton",
        "boiled potatoes",
        "baked sweet potatoes",
        "kummel",
        "new green peas",
        "ceylon tea",
        "clam juice cocktail",
        "vermouth",
        "pommard",
        "biscuit glace",
        "broiled bacon",
        "hamburger steak",
        "hashed browned potatoes",
        "lobster",
        "cottage cheese",
        "potatoes",
        "english breakfast tea",
        "fruchte",
        "honey",
        "peaches",
        "endive salad",
        "strawberries",
        "cotuits",
        "clam juice",
        "queen olives",
        "cold tongue",
        "romaine",
        "boiled onions",
        "filet mignon",
        "prime ribs of beef",
        "string beans",
        "french string beans",
        "prime ribs of beef au jus",
        "mayonnaise dressing",
        "custard pie",
        "hearts of celery",
        "french bread",
        "mixed pickles",
        "baked idaho potato",
        "tomato salad",
        "oysters",
        "mayonnaise",
        "roast beef sandwich",
        "swiss cheese sandwich",
        "julienne potatoes",
        "fried oysters",
        "mixed ice cream",
        "spring lamb, mint sauce",
        "danish pastry",
        "cucumber salad",
        "blue points",
        "lemon ice",
        "dates",
        "oolong tea",
        "corn muffins",
        "stilton cheese",
        "sauternes",
        "kase",
        "anchovy salad",
        "spring lamb",
        "baked potato",
        "cape cod oysters",
        "sliced fresh pineapple",
        "mutton",
        "raisin cake",
        "strawberry short cake",
        "honey dew melon",
        "french fried potatoes",
        "kaffee hag",
        "poached eggs",
        "hashed brown potatoes",
        "moet & chandon, white seal",
        "corn bread",
        "oyster bay asparagus",
        "fromage",
        "fancy cakes",
        "escarole",
        "horlick's malted milk",
        "pistache ice cream",
        "clam cocktail",
        "guava jelly",
        "medoc",
        "boiled sweet potatoes",
        "chilled tomato juice",
        "lima beans",
        "fresh fruit salad",
        "pommery sec",
        "bacon",
        "fruit cake",
        "baked apples",
        "eggs to order",
        "fried ham",
        "toasted crackers",
        "american cheese",
        "mashed potatoes",
        "corned beef sandwich",
        "poussin",
        "tom collins",
        "new string beans",
        "chocolate ice cream",
        "stilton",
        "royal squab",
        "haut sauternes",
        "celeri     ",
        "porterhouse steak",
        "apollinaris water",
        "stuffed tomatoes",
        "coffee with cream",
        "potato salad",
        "vegetable soup",
        "clam fritters",
        "fresh shrimp cocktail",
        "roquefort dressing",
        "preserved figs",
        "claret",
        "salade",
        "peas",
        "chablis",
        "stuffed mangoes",
        "kirschwasser",
        "omelette, plain",
        "dubonnet",
        "laubenheimer",
        "corned beef and cabbage",
        "bermuda potatoes",
        "whiskey sour",
        "sauerkraut juice",
        "romaine salad",
        "cafe",
        "hearts of lettuce",
        "roast turkey",
        "sliced oranges",
        "broiled chicken",
        "smoked beef",
        "sliced pineapple",
        "squash",
        "instant postum",
        "boiled ham",
        "sherbet",
        "jam",
        "strawberry shortcake",
        "gruyere cheese",
        "chicory",
        "fresh milk",
        "english mutton chop",
        "potatoes, french fried",
        "meringue glace",
        "iced tea",
        "wine jelly",
        "stewed rhubarb",
        "liebfraumilch",
        "rice",
        "buttered beets",
        "tokay grapes",
        "cream of tomato soup",
        "scotch woodcock",
        "mock turtle soup",
        "chambertin",
        "spaghetti",
        "stuffed tomato",
        "apricots",
        "plain omelet",
        "hochheimer",
        "sponge cake",
        "pousse cafe",
        "potatoes, boiled",
        "table celery",
        "broiled fresh mushrooms",
        "fresh strawberries",
        "marmelade",
        "yorkshire buck",
        "hot roast beef sandwich",
        "canadian club",
        "petite marmite",
        "canadian cheese",
        "salted almonds",
        "bluefish",
        "pie a la mode",
        "boiled new potatoes",
        "huitres",
        "friandises",
        "broccoli",
        "kippered herring",
        "lemon meringue pie",
        "au gratin potatoes",
        "bel paese cheese",
        "beefsteak",
        "lobster a la newburg",
        "daiquiri",
        "thousand island dressing",
        "saratoga potatoes",
        "spanish omelette",
        "grand marnier",
        "pistachio ice cream",
        "liederkranz",
        "broiled spring chicken",
        "petit fours",
        "seltzer",
        "cointreau",
        "grape fruit",
        "macaroni",
        "pickled lamb's tongue",
        "hot chocolate",
        "salat",
        "hafergrutze",
        "sirloin steak with mushrooms",
        "radieschen",
        "spaghetti au gratin",
        "cherries",
        "ices in souvenir",
        "green tea",
        "creme de cacao",
        "potatoes, mashed",
        "stuffed green peppers",
        "mixed nuts",
        "budweiser",
        "imported swiss cheese",
        "potatoes, lyonnaise",
        "peach ice cream",
        "sliced orange",
        "rice cakes",
        "potatoes parisienne",
        "french rolls",
        "broiled bluefish",
        "sarsaparilla",
        "bouillon",
        "shredded wheat",
        "consomme julienne",
        "tangerines",
        "apricot brandy",
        "boston brown bread",
        "grapefruit supreme",
        "pickled onions",
        "hearts of lettuce salad",
        "orange pekoe tea",
        "american",
        "sanka coffee",
        "milk toast",
        "iced coffee",
        "rhubarb pie",
        "assorted cold cuts",
        "sliced bananas",
        "cheese sandwich",
        "rice pudding",
        "spinach with egg",
        "fancy ices",
        "red leg partridge",
        "pork and beans",
        "chutney",
        "orange sherbet",
        "chocolate parfait",
        "lobster cocktail",
        "haut sauterne",
        "apricot water ice",
        "chow chow",
        "swiss",
        "apple",
        "cranberry sauce",
        "canape of anchovies",
        "chicken consomme",
        "german pancake",
        "graves",
        "tapioca pudding",
        "apricot pie",
        "bar-le-duc",
        "chartreuse, yellow",
        "american cheese",
        "club sandwich",
        "roast lamb",
        "gin fizz",
        "cheese cake",
        "cauliflower au gratin",
        "clam broth",
        "chocolate eclairs",
        "extra sirloin steak",
        "philadelphia cream cheese",
        "cocoanut pie",
        "cherry pie",
        "english pheasant",
        "wheat cakes",
        "dipped toast",
        "bismarck herring",
        "prunes",
        "ham omelet",
        "assorted cheese",
        "cheddar cheese",
        "codfish cakes",
        "soda",
        "american cheese sandwich",
        "fresh vegetable salad",
        "raspberry sherbet",
        "green peas",
        "apple pie",
        "martini cocktail",
        "boston baked beans",
        "fried oysters",
        "strawberry ice cream",
        "dutch cheese",
        "halibut steak",
        "ruddy duck",
        "milk, per glass",
        "carciofini",
        "nachtisch",
        "pate de foie gras",
        "eggs, fried",
        "sliced peaches",
        "celeri",
        "preserved peaches",
        "tenderloin steak with mushrooms",
        "fruit in season",
        "roastbeef",
        "rum",
        "baked beans",
        "bluepoints",
        "potatoes lyonnaise",
        "cervelat",
        "caviar, special importation",
        "fried hominy",
        "lemon sherbet",
        "dandelion salad",
        "camembert cheese",
        "lemon soda",
        "lobster newburg",
        "port salut",
        "combination salad",
        "extra special heavy cream",
        "breakfast bacon",
        "egg plant",
        "omelet, plain",
        "rudesheimer",
        "rye bread",
        "leberwurst",
        "manhattan cocktail",
        "fresh string beans",
        "fried clams",
        "cole slaw",
        "ox tongue",
        "chocolate eclair",
        "sardellen",
        "cheese and crackers",
        "corn fritters",
        "french asparagus",
        "spanish olives",
        "potatoes, baked",
        "potato croquettes",
        "caramel custard",
        "crabmeat cocktail",
        "crab flake cocktail",
        "strawberry ice cream",
        "champagne",
        "clam stew ",
        "asparagus tips",
        "orange ice",
        "chicken salad sandwich",
        "mixed green salad",
        "watercress salad",
        "fried oyster crabs",
        "potatoes hashed in cream",
        "poland water",
        "chef's salad",
        "apfelsinen",
        "baked alaska",
        "sliced chicken",
        "apple juice",
        "coupe of fresh strawberries, favorite",
        "petits fours",
        "camembert cheese",
        "celery salad",
        "lyon sausage",
        "russian caviar",
        "fresh strawberry ice cream",
        "cold chicken",
        "mixed ice cream",
        "champagne cocktail",
        "cocktail",
        "haricots verts",
        "grape nuts",
        "blueberry pie",
        "eclair",
        "preserved skinless figs",
        "supreme of fruit, astor",
        "ice cream",
        "julienne",
        "stewed pears",
        "onion soup au gratin",
        "cup custard",
        "obst",
        "soft shell crabs",
        "crackers and milk",
        "butter",
        "assorted fruit",
        "stinger",
        "lettuce and tomato",
        "saucisson de lyon",
        "westphal\u00e3\u00adan ham",
        "boiled rice",
        "raspberries",
        "caviar sandwich",
        "cold turkey",
        "crab meat cocktail",
        "pot of tea",
        "spaghetti italienne",
        "heart of lettuce salad",
        "oyster patties",
        "french toast",
        "old fashioned",
        "melon in season",
        "alligator pear salad",
        "anchovis",
        "cook's imperial",
        "zeltinger",
        "muffins",
        "amandes salees",
        "stuffed olives",
        "port du salut",
        "pastry",
        "bent's water crackers",
        "side car",
        "eggs, boiled",
        "chianti",
        "eggs, scrambled",
        "peach short cake",
        "nuts and raisins",
        "fried soft shell crabs",
        "clams",
        "stewed potatoes",
        "terrapin",
        "frische milch",
        "potato",
        "mumm's extra dry",
        "compot",
        "marinated herring",
        "coffee, pot",
        "clear green turtle soup",
        "salami",
        "chicken okra soup",
        "bacardi cocktail",
        "california orange",
        "apple sauce",
        "neapolitan ice cream",
        "endive salad",
        "beef",
        "cognac",
        "macon",
        "neapolitan",
        "figs in syrup",
        "lady fingers",
        "stuffed figs and dates",
        "oatmeal porridge",
        "mixed salad",
        "cheese omelette",
        "strawberry jam",
        "macaroni au gratin",
        "fried scallops",
        "nesselrode pudding",
        "sliced bananas and cream",
        "irish stew",
        "cafe turc",
        "oyster fry",
        "fancy ice cream",
        "fresh mackerel",
        "vienna bread",
        "grape juice",
        "escarole salad",
        "clysmic",
        "brawn",
        "brook trout",
        "fried onions",
        "fresh strawberries and cream",
        "bologna sausage",
        "assorted nuts",
        "welsh rarebit",
        "chicken sandwich",
        "pear \"au feu d'enfer\"",
        "chicken (half)",
        "clear green turtle",
        "rockaways",
        "biscuits",
        "fried bacon",
        "blackberries",
        "coca cola",
        "salted almonds",
        "young onions",
        "onions",
        "club soda",
        "ribs of beef ",
        "roast lamb, mint sauce",
        "graham rolls",
        "new potatoes",
        "cream cheese",
        "squab chicken (half)",
        "old tom gin",
        "shrimp",
        "concombres",
        "steamed rice",
        "drambuie",
        "coffee ice cream",
        "whitebait",
        "consomme vermicelli",
        "crab meat salad",
        "india relish",
        "gebackene kartoffeln",
        "rice and milk",
        "lobster, newburg",
        "fresh asparagus",
        "venison",
        "sparkling moselle",
        "lettuce and tomato sandwich",
        "ham sandwich",
        "curried chicken with rice",
        "gin rickey",
        "cocktails",
        "head cheese",
        "cold lamb",
        "hot mince pie",
        "assorted fresh fruit",
        "soup du jour",
        "scotch grouse",
        "cold rice pudding",
        "porterhouse steak with mushrooms",
        "pear melba",
        "sirloin steak",
        "chicory salad",
        "brandy peaches",
        "plain lemonade",
        "coffee",
        "roast turkey, cranberry sauce",
        "sherry flip",
        "mangoes",
        "salade de saison",
        "raspberry jam",
        "fresh fruit cocktail",
        "fried sweet potatoes",
        "fish cakes",
        "claret punch",
        "westphalia ham",
        "lettuce and tomatoes",
        "lamb, mint sauce",
        "guinness' stout",
        "rolls and butter",
        "spinach with egg",
        "fried smelts",
        "tea, pot",
        "oyster stew",
        "maple syrup",
        "macedoine salad",
        "canvas-back duck",
        "sirloin steak with onions",
        "coffee, per pot",
        "smoked beef tongue",
        "tutti frutti ice cream",
        "pim-olas",
        "strawberries with cream",
        "corn cakes",
        "ham omelette",
        "waffles",
        "chocolade",
        "spanish omelet",
        "sloe gin",
        "red-head duck",
        "glass of milk",
        "sliced bananas with cream",
        "brandy",
        "vermouth, italian",
        "canape of caviar",
        "julienne soup",
        "eggs, shirred",
        "salmon salad",
        "broiled squab",
        "oyster bay asparagus",
        "vienna rolls",
        "mettwurst",
        "chartreuse, green",
        "silver fizz",
        "crab salad",
        "pickled oysters",
        "alligator pear",
        "caviar canape",
        "pont l'eveque cheese",
        "prune juice",
        "tongue sandwich",
        "pistache ice cream",
        "mock turtle",
        "new asparagus",
        "gervais",
        "tea, per pot",
        "potatoes julienne",
        "gumbo",
        "malted milk",
        "chicken soup",
        "capon",
        "beef consomme",
        "corn flakes",
        "crabflake cocktail",
        "assorted hors d'oeuvres",
        "ham and eggs",
        "ribs of prime beef",
        "beef tongue",
        "cream, per glass",
        "sauerkraut",
        "stewed oysters",
        "finnan haddie",
        "sloe gin fizz",
        "american coffee",
        "crab meat cocktail",
        "liver and bacon",
        "fresh mushrooms",
        "lemon pie",
        "pie",
        "cold consomme",
        "chocolate sundae",
        "consomme en tasse",
        "dill pickle",
        "port du salut cheese",
        "pink lady",
        "bacon and eggs",
        "broiled chicken (half)",
        "country sausage",
        "potatoes, saratoga",
        "turnips",
        "graham wafers",
        "broiled oysters",
        "gekochte kartoffeln",
        "stewed strawberries",
        "cafe noir",
        "waldorf salad",
        "baked apples with cream",
        "st. estephe",
        "liver sausage",
        "boston cream pie",
        "spring onions",
        "lamb chop",
        "potatoes o'brien",
        "tomato broth",
        "roast beef",
        "moet & chandon",
        "veuve clicquot, yellow label",
        "roast potatoes",
        "fruits in season",
        "boned capon",
        "eclairs",
        "spring chicken",
        "cauliflower, polonaise",
        "hashed browned potatoes",
        "corn fritters",
        "fruit salad",
        "lemon water ice",
        "milchreis",
        "caviar on toast",
        "rostbraten",
        "chateau yquem",
        "spring turkey (half)",
        "clam broth",
        "new beets",
        "lemon ice cream",
        "crullers",
        "cacao",
        "jamaica rum",
        "potatoes, fried",
        "water crackers",
        "petits pois",
        "chocolate layer cake",
        "apple fritters",
        "pineapple water ice",
        "schweizer k\u00e3\u00a4se",
        "french sardines",
        "fresh fruit cup",
        "long island duckling",
        "cream toast",
        "malaga grapes",
        "boiled onions, cream sauce",
        "hamburg steak",
        "margaux",
        "beaune",
        "golden plover",
        "french vanilla ice cream",
        "jelly",
        "combination salad",
        "ginger",
        "ruinart brut",
        "lamb chops (2)",
        "pumpkin pie",
        "olives",
        "sliced cucumbers",
        "old tom",
        "strained honey",
        "tomato omelette",
        "vegetable salad",
        "pineapple cheese",
        "china tea",
        "linden tea",
        "german fried potatoes",
        "blackberry brandy",
        "burger",
        "hamburger",
        "bigmac",
        "mcdonalds",
        "hungry jacks",
        "mcdonald's",
        "kfc",
        "schnitz",
        "d'lish fish",
        "grill'd",
        "fries",
        "fried",
        "chips",
        "fries",
        "burger",
        "hamburger",
        "hot dog",
        "nugget",
        "onion rings",
        "pizza",
        "sandwich",
        "sausage",
        "taco",
        "chicken",
        "wing",
        "fish",
        "duck",
        "beef",
        "steak",
        "salad",
        "rice",
        "sushi",
        "pasta",
        "bread",
        "pancakes",
        "muffins",
        "cheesecake",
        "tacos",
        "tomato",
        "rib",
        "ribs",
        "candy",
        "sugar",
        "fruit",
        "fruits",
        "subway",
        "grain",
        "cookie",
        "seafood",
        "sausage",
        "dumplings",
        "noodles",
        "sandwiches",
        "nut",
        "shellfish",
        "avocado",
        "blackberry",
        "grapes",
        "cherry",
        "lemon",
        "strawberry",
        "peach",
        "plum",
        "lime",
        "asparagus",
        "broccoli",
        "onion",
        "garlic",
        "mushroom",
        "mushrooms",
        "cucumber",
        "celery",
        "peas",
        "potato",
        "cabbage",
        "carrot",
        "almonds",
        "peanuts",
        "soda",
        "cola",
        "pepsi",
        "zinger box"

    ]